PARKING_AVG_THRESHOLD = 80
PARKING_LOT_CRITICAL_THRESHOLD = 95
GOVERNANCE_DELAY_SHORT = 1.5
GOVERNANCE_DELAY_LONG = 1.6
CONFIDENCE_THRESHOLD_LOW = 80
CONFIDENCE_GATE_B = 74
CONFIDENCE_GATE_A = 78
CONFIDENCE_DEFAULT = 82
